name: Node.js CI

on: [push,workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  
  build-node:
    runs-on: ubuntu-latest
    needs: say-hello

    strategy:
      matrix:
        # node-version: [18.x, 20.x, 22.x]
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  deploy-dev:
    needs: build-node
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "Deploying to DEV app service $TEST_APP_SERVICE_NAME"

  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - run: echo "Deploying to UAT app service $TEST_APP_SERVICE_NAME"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploying to PROD app service $TEST_APP_SERVICE_NAME"
